# Generated by Django 3.2.5 on 2021-07-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20210709_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture2',
            field=models.ImageField(upload_to='picture2/'),
        ),
    ]
