# Generated by Django 3.2.5 on 2021-07-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_category_picture2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='picture2',
        ),
    ]
