# Generated by Django 3.2.5 on 2021-07-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_category2_skills2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills2',
            new_name='Squads',
        ),
        migrations.AlterModelOptions(
            name='category2',
            options={'verbose_name': 'Squad', 'verbose_name_plural': 'Squads'},
        ),
        migrations.RenameField(
            model_name='squads',
            old_name='skill_name',
            new_name='player_name',
        ),
    ]
