# Generated by Django 3.2.5 on 2021-07-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_auto_20210710_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='link',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='hovertext',
            field=models.CharField(default='By: Player name', max_length=50),
        ),
    ]
